#!/bin/bash

sed -i -e 's,^exit 0$,[ -f /opt/spark/firstboot.sh ] \&\& sh /opt/spark/firstboot.sh; exit 0,' /etc/rc.local

cat >> /opt/spark/firstboot.sh <<EOF
#!/bin/sh
chown -R ubuntu:ubuntu /opt/spark
chown -R ubuntu:ubuntu /etc/hadoop
rm /opt/spark/firstboot.sh
EOF

# Setting up JAVA_HOME and PATH for Java not in /usr/bin
JAVA_NAME=`ls -1 /usr/java`
sed -i '$a # Setting up JAVA_HOME' /etc/profile
sed -i "\$a export JAVA_HOME=/usr/java/$JAVA_NAME/" /etc/profile
sed -i "\$a export PATH=\$PATH:/usr/java/$JAVA_NAME/bin" /etc/profile

# Updating alternatives for Java
update-alternatives --install "/usr/bin/java" "java" "/usr/java/$JAVA_NAME/bin/java" 1
update-alternatives --install "/usr/bin/javac" "javac" "/usr/java/$JAVA_NAME/bin/javac" 1
update-alternatives --install "/usr/bin/javaws" "javaws" "/usr/java/$JAVA_NAME/bin/javaws" 1

update-alternatives --set java /usr/java/$JAVA_NAME/bin/java
update-alternatives --set javac /usr/java/$JAVA_NAME/bin/javac
update-alternatives --set javaws /usr/java/$JAVA_NAME/bin/javaws


