#!/bin/bash
# This script installs Spark
# More documentation in the README.md file

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

tmp_dir=/tmp/spark
pushd $tmp_dir


echo "Extracting SPARK"
spark_url=$(cat spark_url.txt)
spark_file=$(basename $spark_url)
extract_folder=$(tar tzf $spark_file | sed -e 's@/.*@@' | uniq)
echo "Decompressing Spark..."
tar xzf $spark_file
rm $spark_file

echo "Moving SPARK to /opt/"
# Placing spark in /opt/spark
mv $extract_folder /opt/spark/
mv spark_url.txt /opt/spark/

if [ -f spark_notebook_url.txt ]; then
    echo "Extracting Spark Noteboook"
    spark_nb_url=$(cat spark_notebook_url.txt)
    spark_nb_file=$(basename $spark_nb_url)
    extract_folder=$(tar tzf $spark_nb_file | sed -e 's@/.*@@' | uniq)
    echo "Decompressing Spark notebook..."
    tar xzf $spark_nb_file
    rm $spark_nb_file
    
    echo "Moving Spark notebook to /opt/"
    # Placing spark notebook in /opt/spark-notebook
    mv $extract_folder /opt/spark-notebook/
    mv spark_notebook_url.txt /opt/spark-notebook/
else
    echo "Warning: no notebook found, will not install"
fi

# DiNoDB
if [ -n "${DIB_SPARK_ADD_DINODB}" ]; then
    echo "Decompressing DiNoDB"
    tar xzf /opt/dinodb.tar.gz
fi


popd
rm -Rf $tmp_dir
