#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

NOTEBOOK_VERSION="0.6.1"
SCALA_VERSION="2.10.4"
NB_HADOOP_DL="unset"
DINODB_URL="https://googledrive.com/host/0B2TbBvh6BGVcfkVIaWhZRXZ4dVRYUjBCWkV0WTAxWENxeUMteVowd1JSXzNDb3gza0U5MXM/dinodb.tar.gz"

tmp_dir=$TARGET_ROOT/tmp/spark
mkdir -p $tmp_dir

# The user is not providing his own Spark distribution package
if [ -z "${SPARK_DOWNLOAD_URL:-}" ]; then
    # Check hadoop version
    # INFO on hadoop versions: http://spark.apache.org/docs/latest/hadoop-third-party-distributions.html
    case "$DIB_CDH_VERSION" in
        5.0)
            SPARK_HADOOP_DL=hadoop2.3
        ;;
        5.3)
            SPARK_HADOOP_DL=hadoop2.4
            NB_HADOOP_DL=hadoop-2.5.0-cdh5.3.2
        ;;
        5.4)
            SPARK_HADOOP_DL=hadoop2.6
            NB_HADOOP_DL=hadoop-2.6.0-cdh5.4.2
        ;;
        CDH4)
            SPARK_HADOOP_DL=cdh4
        ;;
        *)
            echo "WARNING: Cloudera CDH version $DIB_CDH_VERSION not supported."
            echo "WARNING: use the SPARK_DOWNLOAD_URL variable to install a custom Spark version."
            exit 1
        ;;
    esac

    SPARK_DOWNLOAD_URL="http://archive.apache.org/dist/spark/spark-$DIB_SPARK_VERSION/spark-$DIB_SPARK_VERSION-bin-$SPARK_HADOOP_DL.tgz"
    NOTEBOOK_DOWNLOAD_URL="https://s3.eu-central-1.amazonaws.com/spark-notebook/tgz/spark-notebook-$NOTEBOOK_VERSION-scala-$SCALA_VERSION-spark-$DIB_SPARK_VERSION-$NB_HADOOP_DL-with-parquet.tgz"
fi

echo "Downloading SPARK"
spark_file=$(basename "$SPARK_DOWNLOAD_URL")
cached_tar="$DIB_IMAGE_CACHE/$spark_file"
$TMP_HOOKS_PATH/bin/cache-url $SPARK_DOWNLOAD_URL $cached_tar
sudo install -D -g root -o root -m 0755 $cached_tar $tmp_dir
echo "$SPARK_DOWNLOAD_URL" > $tmp_dir/spark_url.txt

#if [ "$NB_HADOOP_DL" != "unset" ]; then
#    echo "Downloading SPARK Notebook"
#    nb_file=$(basename "$NOTEBOOK_DOWNLOAD_URL")
#    cached_tar="$DIB_IMAGE_CACHE/$nb_file"
#    $TMP_HOOKS_PATH/bin/cache-url $NOTEBOOK_DOWNLOAD_URL $cached_tar
#    sudo install -D -g root -o root -m 0755 $cached_tar $tmp_dir
#    echo "$NOTEBOOK_DOWNLOAD_URL" > $tmp_dir/spark_notebook_url.txt
#else
#    echo "Warning: could not find a notebook package matching the selected spark version, no notebook will be installed"
#fi

echo "Downloading DiNoDB"
dinodb_file=$(basename "$DINODB_URL")
cached_tar="$DIB_IMAGE_CACHE/$dinodb_file"
pushd $TARGET_ROOT/opt
sudo wget $DINODB_URL
sudo chown root.root dinodb.tar.gz
sudo chmod 644 dinodb.tar.gz
popd
#sudo install -D -g root -o root -m 0755 $cached_tar $TARGET_ROOT/opt/

