#!/bin/bash

mkdir /run/hadoop
chown hadoop:hadoop /run/hadoop/
#mkdir -p /home/ubuntu/.ssh
#touch /home/ubuntu/.ssh/authorized_keys
#chown -R ubuntu:ubuntu /home/ubuntu
#chown -R ubuntu:ubuntu /etc/hadoop

mkdir -p /var/run/hadoop ; chown hadoop:hadoop /var/run/hadoop
mkdir -p /mnt/log/hadoop ; chown hadoop:hadoop /mnt/log/hadoop

